apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spoved-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
