mirrors:
  docker.io:
    endpoint:
      - "https://registry.docker-cn.com"
      - "https://docker.mirrors.ustc.edu.cn"
      - "https://registry-1.docker.io"
      - "https://registry.cn-hangzhou.aliyuncs.com"
